version: '3'
services:
  frontend:
    build: ./frontend
    image: marsukat-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://192.168.100.39:3000/api/v1  # Your network IP

  backend:
    build: ./backend
    image: marsukat-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://192.168.100.39:5173  # Your network IP
