import {
  LayoutDashboard,
  ShoppingBag,
  Calendar,
  PhilippinePeso,
  Wrench,
  Building2,
  Phone,
  Home,
  School,
  BookOpen,
  GraduationCap,
  ShieldCheck,
  FileSpreadsheet,
  Building,
  Factory,
  BoxSelect,
  Tag,
  Scale,
  Warehouse,
  PackageSearch,
  ClipboardList,
  Store,
  KeyRound,
  CalendarRange,
  Shirt,
  Scissors,
  GraduationCap as GownIcon,
  Factory as FactoryProduction,
  Package,
  Box,
  Boxes,
  BookOpenCheck,
  BarChart3,
  FileText,
} from "lucide-react";

export const menuItems = {
  PublicMenu: [
    {
      title: "Home",
      icon: <Home />,
      path: () => "/",
      description: "Go to homepage",
    },
    {
      title: "About",
      icon: <School />,
      path: () => "/about",
      description: "Learn about us",
    },
    {
      title: "Contact",
      icon: <Phone />,
      path: () => "/contact-us",
      description: "Get in touch",
    },
    {
      title: "FAQ",
      icon: <BookOpen />,
      path: () => "/faq",
      description: "Frequently asked questions",
    },
  ],
  Student: [
    {
      title: "Dashboard",
      icon: <GraduationCap />,
      path: (id) => `/student/dashboard/${id}`,
      description: "View your dashboard",
    },
    {
      title: "Orders",
      icon: <ShoppingBag />,
      path: (id) => `/student/orders/${id}`,
      description: "Manage your orders",
    },
    {
      title: "Schedules",
      icon: <Calendar />,
      path: (id) => `/student/schedules/${id}`,
      description: "View your schedules",
    },
  ],
  SuperAdmin: [
    {
      title: "Dashboard",
      icon: <ShieldCheck />,
      path: (id) => `/superadmin/dashboard/${id}`,
      description: "Overview of system",
    },
    {
      title: "Create Job Order",
      icon: <FileSpreadsheet />,
      path: () => "/superadmin/create-job-order",
      description: "Create a new job order",
    },
    {
      title: "Maintenance",
      icon: <Wrench />,
      type: "accordion",
      items: [
        {
          title: "Levels",
          icon: <Building />,
          path: () => "/superadmin/maintenance/levels",
          description: "Manage levels",
        },
        {
          title: "Departments",
          icon: <Factory />,
          path: () => "/superadmin/maintenance/departments",
          description: "Manage departments",
        },
        {
          title: "Department Levels Options",
          icon: <Building2 />,
          path: () => "/superadmin/maintenance/department-levels",
          description: "Manage department levels",
        },
        {
          title: "Units",
          icon: <BoxSelect />,
          path: () => "/superadmin/maintenance/units",
          description: "Manage units",
        },
        {
          title: "Categories",
          icon: <Tag />,
          path: () => "/superadmin/maintenance/categories",
          description: "Manage categories",
        },
        {
          title: "Sizes",
          icon: <Scale />,
          path: () => "/superadmin/maintenance/sizes",
          description: "Manage sizes",
        },
        {
          title: "Prices",
          icon: <PhilippinePeso />,
          path: () => "/superadmin/maintenance/prices",
          description: "Manage prices",
        },
        {
          title: "Raw Material Type",
          icon: <Warehouse />,
          path: () => "/superadmin/maintenance/raw-material-types",
          description: "Manage raw material types",
        },
        {
          title: "Product Types",
          icon: <PackageSearch />,
          path: () => "/superadmin/maintenance/product-types",
          description: "Manage product types",
        },
      ],
    },
  ],
  JobOrder: [
    {
      title: "Dashboard",
      icon: <LayoutDashboard />,
      path: (id) => `/job-order/dashboard/${id}`,
      description: "Overview of system",
    },
    {
      title: "Transactions",
      icon: <Wrench />,
      type: "accordion",
      items: [
        {
          title: "Student Orders",
          icon: <ClipboardList />,
          path: () => "/job-order/student-orders",
          description: "Manage student orders",
        },
        {
          title: "Commercial Orders",
          icon: <Store />,
          path: () => "/job-order/commercial-orders",
          description: "Manage commercial orders",
        },
        {
          title: "Rentals",
          icon: <KeyRound />,
          path: () => "/job-order/rentals",
          description: "Manage rentals",
        },
        {
          title: "Schedules",
          icon: <CalendarRange />,
          path: () => "/job-order/schedules",
          description: "Manage schedules of students and commercial jobs",
        },
      ],
    },
    {
      title: "Productions",
      icon: <Factory />,
      type: "accordion",
      items: [
        {
          title: "Uniform Production",
          icon: <Scissors />,
          path: () => "/job-order/productions/school-uniforms",
          description: "Manage uniform production",
        },
        {
          title: "Academic Gowns Production",
          icon: <GownIcon />,
          path: () => "/job-order/productions/academic-gowns",
          description: "Manage academic gowns production",
        },
        {
          title: "Commercial Job Production",
          icon: <FactoryProduction />,
          path: () => "/job-order/productions/commercial-jobs",
          description: "Manage commercial job production",
        },
        {
          title: "Other Productions",
          icon: <Package />,
          path: () => "/job-order/productions/others",
          description: "Manage other productions",
        },
      ],
    },
    {
      title: "Inventory",
      icon: <Boxes />,
      type: "accordion",
      items: [
        {
          title: "Raw Materials Inventory",
          icon: <Box />,
          path: () => "/job-order/inventory/raw-materials",
          description: "Manage raw materials inventory",
        },
        {
          title: "School Uniform Inventory",
          icon: <Shirt />,
          path: () => "/job-order/inventory/school-uniforms",
          description: "Manage school uniform inventory",
        },
        {
          title: "Academic Gown Inventory",
          icon: <GownIcon />,
          path: () => "/job-order/inventory/academic-gowns",
          description: "Manage academic gown inventory",
        },
        {
          title: "Commercial Job Inventory",
          icon: <Package />,
          path: () => "/job-order/inventory/commercial-jobs",
          description: "Manage commercial job inventory",
        },
        {
          title: "Others Inventory",
          icon: <Warehouse />,
          path: () => "/job-order/inventory/others",
          description: "Manage other inventory items",
        },
      ],
    },
    {
      title: "Reports",
      icon: <FileText />,
      type: "accordion",
      items: [
        {
          title: "Sales Report",
          icon: <BarChart3 />,
          path: () => "/job-order/reports/sales",
          description: "View sales reports",
        },
        {
          title: "Accomplishment Reports",
          icon: <BookOpenCheck />,
          path: () => "/job-order/reports/accomplishments",
          description: "View accomplishment reports",
        },
      ],
    },
  ],
};
