import {
  LayoutDashboard,
  ShoppingBag,
  Calendar,
  Scissors,
  UserPlus,
  Wrench,
  Building2,
  Phone,
  Home,
  School,
  BookOpen,
  GraduationCap,
  ShieldCheck,
  FileSpreadsheet,
  Building,
  Factory,
  BoxSelect,
  Tag,
  Scale,
  Warehouse,
  PackageSearch,
  ListTodo,
  ScrollText,
  PhilippinePeso,
} from "lucide-react";

export const menuItems = {
  PublicMenu: [
    {
      title: "Home",
      icon: <Home />,
      path: () => "/",
      description: "Go to homepage",
    },
    {
      title: "About",
      icon: <School />,
      path: () => "/about",
      description: "Learn about us",
    },
    {
      title: "Contact",
      icon: <Phone />,
      path: () => "/contact-us",
      description: "Get in touch",
    },
    {
      title: "FAQ",
      icon: <BookOpen />,
      path: () => "/faq",
      description: "Frequently asked questions",
    },
  ],
  Student: [
    {
      title: "Dashboard",
      icon: <GraduationCap />,
      path: (id) => `/student/dashboard/${id}`,
      description: "View your dashboard",
    },
    {
      title: "Orders",
      icon: <ShoppingBag />,
      path: (id) => `/student/orders/${id}`,
      description: "Manage your orders",
    },
    {
      title: "Schedules",
      icon: <Calendar />,
      path: (id) => `/student/schedules/${id}`,
      description: "View your schedules",
    },
  ],
  SuperAdmin: [
    {
      title: "Dashboard",
      icon: <ShieldCheck />,
      path: (id) => `/superadmin/dashboard/${id}`,
      description: "Overview of system",
    },
    {
      title: "Create Job Order",
      icon: <FileSpreadsheet />,
      path: () => "/superadmin/create-job-order",
      description: "Create a new job order",
    },
    {
      title: "Create Super Admin",
      icon: <UserPlus />,
      path: () => "/superadmin/create-super-admin",
      description: "Create a new super admin",
    },
    {
      title: "Maintenance",
      icon: <Wrench />,
      type: "accordion",
      items: [
        {
          title: "Levels",
          icon: <Building />,
          path: () => "/superadmin/maintenance/levels",
          description: "Manage levels",
        },
        {
          title: "Departments",
          icon: <Factory />,
          path: () => "/superadmin/maintenance/departments",
          description: "Manage departments",
        },
        {
          title: "Department Levels Options",
          icon: <Building2 />,
          path: () => "/superadmin/maintenance/department-levels",
          description: "Manage department levels",
        },
        {
          title: "Units",
          icon: <BoxSelect />,
          path: () => "/superadmin/maintenance/units",
          description: "Manage units",
        },
        {
          title: "Categories",
          icon: <Tag />,
          path: () => "/superadmin/maintenance/categories",
          description: "Manage categories",
        },
        {
          title: "Sizes",
          icon: <Scale />,
          path: () => "/superadmin/maintenance/sizes",
          description: "Manage sizes",
        },
        {
          title: "Prices",
          icon: <PhilippinePeso />,
          path: () => "/superadmin/maintenance/prices",
          description: "Manage prices",
        },
        {
          title: "Raw Material Type",
          icon: <Warehouse />,
          path: () => "/superadmin/maintenance/raw-material-types",
          description: "Manage raw material types",
        },
        {
          title: "Product Types",
          icon: <PackageSearch />,
          path: () => "/superadmin/maintenance/product-types",
          description: "Manage product types",
        },
      ],
    },
  ],
  Staff: [
    {
      title: "Dashboard",
      icon: <LayoutDashboard />,
      path: () => "/staff/dashboard",
      description: "Staff overview",
    },
    {
      title: "Orders",
      icon: <ScrollText />,
      path: () => "/staff/orders",
      description: "Process orders",
    },
    {
      title: "Production",
      icon: <Scissors />,
      path: () => "/staff/production",
      description: "Production management",
    },
    {
      title: "Tasks",
      icon: <ListTodo />,
      path: () => "/staff/tasks",
      description: "View assigned tasks",
    },
  ],
};
